Source/Components/Item Description/MLBusinessItemDescriptionView.swift

MLBusinessItemDescription numberOfLines

---

Source/Components/Commons/DownloadApp/MLBusinessDownloadAppView.swift
Source/Components/Discount/MLBusinessDiscountBoxView.swift

DownloadAppView UI improvements:

Show title in discountBoxView when there is not subtitle

---

Source/Components/AnimatedButton/MLBusinessAnimatedButton.swift

Se setea el estado Disable del botón al estilo MLButtons.

Setting disable state

---

Source/Components/Discount/Internal/MLBusinessDiscountSingleItemView.swift
Source/Components/Discount/MLBusinessDiscountBoxView.swift

- Added overlay to discount box view component. 
- Dynamic height size of discount box view component.
@tomidelucca @juansanzone

Added overlay to discount box view component. Dynamic height size of discount box view component.

---

CHANGELOG.md
Example/Example_BusinessComponents/MockData/DiscountTrackerData.swift
Source/Commons/MLBusinessDiscountTrackerProtocol.swift
Source/Components/Discount/MLBusinessDiscountBoxView.swift

- Se modificó el protocolo MLBusinessDiscountTrackerProtocol

Discount tracker protocol updated

---

Source/Components/Discount/MLBusinessDiscountBoxView.swift

- Modifiqué la la función UpdateUI para que haga el calculo del espaciado del componente correctamente.

Fixed margins on discountBoxView

---

Source/Components/Touchpoints/MLBusinessTouchpointsTracker.swift

- Updated print logic in MLBusinessTouchpointsView

Updated print logic in MLBusinessTouchpointsView

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to version 1.9.1

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.10.0

---

Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselCollectionItemView.swift
Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselCollectionView.swift
Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselCollectionViewCell.swift
Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselModel.swift
Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselView.swift
Source/Core/Extensions/UIColor+Shades.swift

- Se agrega la card de categories a carousel
- Se corrigen otras cositas

Added categories card to carousel

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.11.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump MLBusinessComponents to 1.12.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.14.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.16.0

---

CHANGELOG.md
Source/Components/ActionCard/MLBusinessActionCardView.swift

Fix shadow of MLBusinessActionCardView

Fix ActionCardView shadow

---

CHANGELOG.md
MLBusinessComponents.podspec

Release MLBusinessComponents 1.17.0

---

CHANGELOG.md
Source/Core/MLBusinessPillView.swift

Resized pill icon

---

Example/Example_BusinessComponents/ViewController.swift

Fixed test app

---

Example/Example_BusinessComponents/ViewController.swift
Source/Components/Sheet/SheetConfiguration.swift
Source/Components/Sheet/SheetContentViewController.swift
Source/Components/Sheet/SheetHeightConstraintManager.swift
Source/Components/Sheet/SheetPanEffects.swift
Source/Components/Sheet/SheetSize.swift
Source/Components/Sheet/SheetSizeManager.swift
Source/Components/Sheet/SheetTransitionAnimations.swift
Source/Components/Sheet/SheetViewController.swift
Source/Components/Sheet/UIViewController-SheetViewController.swift
Source/Core/Extensions/UIView+Autolayout.swift

Primera implementación de un Sheet View Controller

Sheet View Controller

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.20.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.21.0

---

CHANGELOG.md
Source/Components/Row/MLBusinessRowView.swift

Fixed row component reuse

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.22.0

---

Example/Example_BusinessComponents.xcodeproj/project.pbxproj
Source/Components/Sheet/SheetConfiguration.swift
Source/Components/Sheet/SheetContentViewController.swift
Source/Components/Sheet/SheetHeightConstraintManager.swift
Source/Components/Sheet/SheetSize.swift
Source/Components/Sheet/SheetSizeManager.swift
Source/Components/Sheet/SheetViewController.swift

* Fixes in sheet
* Se agregan nuevos tamaños :) 

improvements in sheet

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.24.0

---

CHANGELOG.md
Source/Components/Sheet/SheetSizeManager.swift
Source/Core/Views/PressableView.swift

Xcode 12 Compatible changes,
- compiling in Xcode 12

iOS 14 API Compatible 

---

MLBusinessComponents.podspec

release 1.25.0

---

CHANGELOG.md
Source/Components/Row/MLBusinessRowView.swift

- Added dynamic with for description on row component

Added dynamic with for description on row component

---

CHANGELOG.md
Source/Components/Discount/Internal/MLBusinessDiscountSingleItemView.swift

- Se corrige el centrado de las imagenes en el touchpoint de GRID.
Antes:
Ahora:

Fixed center logo on grid touchpoint

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.26.0

---

CHANGELOG.md
MLBusinessComponents.podspec

- Bump de version.
- [ x Feature or Improvement

Bump to 1.29.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.31.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump to 1.32.0

---

CHANGELOG.md
MLBusinessComponents.podspec

bump 1.34.1

---

CHANGELOG.md
Source/Components/Touchpoints/Types/Carousel/MLBusinessCarouselContainerView .swift

Fix card spaces when we have a full card type 
antes | después
----------- | -----------

Fix card spaces when we have a full card type

---

CHANGELOG.md
MLBusinessComponents.podspec

bump version 1.39.0

---

CHANGELOG.md
Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemView.swift

Fix - Algunos parametros de la firma del touchpoint FlexCoverCarousel no estaban siendo tomados en cuenta al momento de dibujar el componente. 
| Ejemplo en borderColor | 
| ------------- | 
|![Captura de Pantalla 2022-06-22 a la(s) 11 18 40](https://user-images.githubusercontent.com/97110592/175076665-4d3be2f1-c7ce-49ba-be1c-13a679597263.png)|

Fix FlexCoverCarousel UI Parameters

---

CHANGELOG.md
MLBusinessComponents.podspec

Merge back 1.41.0

---

CHANGELOG.md
Source/Components/Touchpoints/Types/FlexCoverCarousel/SkeletonView/MLBusinessFlexCoverCarouselSkeletonItemView.swift

Skeleton View for new Touchpoint
| iPhone 13 max |  iPhone SE |
| ------------- | ------------- | 
| ![Captura de Pantalla 2022-07-05 a la(s) 16 58 53](https://user-images.githubusercontent.com/97110592/177551598-d988d315-6ff1-4d4e-9f0a-91254e0f4b52.png) | ![Captura de Pantalla 2022-07-05 a la(s) 16 50 16](https://user-images.githubusercontent.com/97110592/177551680-28ff98d3-bd38-495a-8acd-0b1be6c5791f.png)|

Added Skeleton View for Touchpoint

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump Version 1.42.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Merge Back - 1.44.0

---

CHANGELOG.md
Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemView.swift
Source/Core/Extensions/UILabel+LineSpacing.swift

- Gradient height changes on FlexCoverCarousel
- Title position dynamic on FlexCoverCarousel
- Paddings changes
https://user-images.githubusercontent.com/96143765/197001574-3a875ee1-e3c7-41fa-92f9-9419b9a1c6ad.MP4

TouchPoint FlexCoverCarousel Adjusts

---

.pre-commit-config.yaml

This PR adds the pre-commit configurations to use websec hook and comments the previous Code Quality hooks.
This PR was created automatically by [websec](https://sites.google.com/mercadolibre.com/websec), please review it to check:
- only the websec-hook configuration is added.
- the CQ hooks are commented.
Lines expected to be added:
```
- repo: https://github.com/mercadolibre/fury_websec-git-hooks
rev: v1.0.0
hooks:
- id: pre_commit_hook
stages: [commit]
- id: post_commit_hook
stages: [post-commit]
```
More information on [workplace post](https://meli.workplace.com/groups/942637169155799/permalink/5076719172414224/).
Feel free to add/remove/modify any other hook except the websec's one. 
Code Quality hooks are **optional**, so if you want to keep them analyzing each commit, you just …

Update pre commit configuration file

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump 1.46.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Mergeback 1.47.0

---

CHANGELOG.md
MLBusinessComponents.podspec

MergeBack 1.48.0

---

CHANGELOG.md
Source/Components/Touchpoints/Types/DynamicCoverCarousel/Card/MLBusinessDynamicCoverCarouselItemView.swift

La intención de este PR es la de crear una funcion que me permita aplicarle alpha a DynamicCoverCarouselItem

Apply alpha to DynamicCoverCarouselItem

---

CHANGELOG.md
MLBusinessComponents.podspec

Mergeback - bump version 1.49

---

CHANGELOG.md
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesModel.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesView.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesViewModel.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesWebView.swift
Source/Components/Touchpoints/Types/DynamicCoverCarousel/Card/MLBusinessDynamicCoverCarouselItemModel.swift
Source/Components/Touchpoints/Types/DynamicCoverCarousel/Card/MLBusinessDynamicCoverCarouselItemView.swift

Se agrega soporte para imagenes animadas en DynamicCoverCarousel. Sigue soportando el image_header que tiene la firma del componente, en caso que no vengan las urls para las animaciones funciona de la misma manera que en la actualidad.
|iphone 13|
|----|
|![Simulator Screen Recording - iPhone 13 - 2022-12-16 at 09 50 56](https://user-images.githubusercontent.com/97110592/208102990-20e1ac30-c122-4791-a9c8-2956ac041d1c.gif)|

[LiveImages] - Animated Images in Dynamic Cover Carousel V1

---

CHANGELOG.md
MLBusinessComponents.podspec

Mergeback 1.49.0

---

CHANGELOG.md
MLBusinessComponents.podspec

Mergeback v1.49.2

---

CHANGELOG.md
Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemModel.swift
Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemView.swift

- Se implementa accesibilidad en FlexCoverCarousel
https://user-images.githubusercontent.com/96143765/209581408-3fbe8faa-c615-4d07-93d7-b57bef2c9b7e.MOV

FlexcoverCarousel accessibility implement

---

CHANGELOG.md
MLBusinessComponents.podspec

[Mergeback] v1.50.0

---

CHANGELOG.md
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesView.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesViewModel.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesWebView.swift

Se soluciona issue que hacia que se vea de manera incorrecta algunas animaciones cuando el usuario scrolleaba el carousel. Se detecto una mal configuración en el clear de las views, ademas ahora se cancela una tarea asincrónica que hacia que la view haga un cambio de estado incorrecto.
|iPhone 13 pro max|
|---|
|![Simulator Screen Recording - iPhone 13 Pro Max - 2023-01-10 at 12 19 25](https://user-images.githubusercontent.com/97110592/211594252-02d446a6-abf1-4a08-888c-2c5e5524ffa6.gif)|

[Live Images] Fix Issue mostrando animaciones de manera incorrecta

---

CHANGELOG.md
MLBusinessComponents.podspec

Mergeback v1.51.0

---

CHANGELOG.md
MLBusinessComponents.podspec

[Mergeback] Bump Version v1.52.0

---

CHANGELOG.md
Source/Components/Touchpoints/LiveImages/ImageAnimationManager.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesCarousel.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesView.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesWebView.swift
Source/Components/Touchpoints/Types/DynamicCoverCarousel/Card/MLBusinessDynamicCoverCarouselViewCell.swift
Source/Components/Touchpoints/Types/DynamicCoverCarousel/Carousel/MLBusinessDynamicCoverCarouselView.swift

Se acomoda la arquitectura para empatar con la definida con Android. Se realizaron tambien algunos renaming de clases/variables por el mismo motivo.
|Sim iPhone 14 Pro|
|----|
|![Simulator Screen Recording - iPhone 14 Pro - 2023-01-24 at 17 47 05](https://user-images.githubusercontent.com/97110592/214408209-8ed08913-7fb1-4b57-90aa-3c29d3dd45cf.gif)|

[LiveImages] - Refactor Mobile Architecture  

---

Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesCarousel.swift

Fix typo in last commit

---

CHANGELOG.md
MLBusinessComponents.podspec

[Mergeback] - Bump Version v1.53.0

---

Source/Components/Touchpoints/LiveImages/ImageAnimationManager.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesCarousel.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesView.swift
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesWebView.swift

Se agregan estados para poder tener seguimiento del componente en sus diferentes etapas. Se realizan tambien algunos cambios en la arquitectura para deja LiveImagesView sin la logica de cambios de estado.

[LiveImages] - New States and MultimediaListener

---

CHANGELOG.md
MLBusinessComponents.podspec

Bump MLBusiness 1.55.0

---

CHANGELOG.md
Example/Example_BusinessComponents/MockData/LoyaltyHeaderData.swift
MLBusinessComponents.podspec
Source/Components/LoyaltyHeader/MLBusinessLoyaltyHeaderData.swift
Source/Components/LoyaltyHeader/MLBusinessLoyaltyHeaderView.swift

Agregamos las modificaciones necesarias para poder recibir nuevos parametros de back asi como la posibilidad de mandar la data del progress ring en null y pintar correctamente el componente.

Benefits component updated

---

CHANGELOG.md
Source/Components/LoyaltyHeader/MLBusinessLoyaltyHeaderData.swift

- Se realizan ajustes para que la firma de LoyaltyHeaderData sea retrocompatible

Retrocompatible Loyal Header

---

CHANGELOG.md
MLBusinessComponents.podspec

Mergeback | 1.56.2

---

CHANGELOG.md
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesWebView.swift

se estaba insertando en el html una input del usuario directamente, pusimos una verificación a ver si es una URL

[CHANGED] solve a vulnerability bug

---

CHANGELOG.md
Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesWebView.swift

Se arregla el issue de pasar un URL y no una String 

[FIX] - Use url se es un url 

---

.pre-commit-config.yaml
Example/Podfile
MLBusinessComponents.podspec
Source/Components/Commons/DownloadApp/MLBusinessDownloadAppView.swift
Source/Components/CrossSelling/MLBusinessCrossSellingBoxView.swift

Using Andes colors

---

CHANGELOG.md
Example/Example_BusinessComponents.xcodeproj/project.pbxproj

Release 1.59.0
