- CHANGELOG.md
- Example/Example_BusinessComponents/MockData/LoyaltyRingData.swift
- MLBusinessComponents.podspec
- Source/Components/Discount/Internal/MLBusinessDiscountSingleItemView.swift
- Source/Components/Discount/MLBusinessDiscountBoxView.swift
- Source/Components/Loyalty/MLBusinessLoyaltyRingView.swift
- Source/Core/UIConstants.swift
- Se ajustan labels en Loyalty Ring View, para estar a la par de lo pedido por UX
- Se ajusta titulo en Discount Box, se agranda de 18 a 20
> Visual changes in labels

- CHANGELOG.md
- Source/Components/Touchpoints/Types/HybridCarousel/Card/Types/Default/MLBusinessHybridCarouselCardDefaultView.swift
- Source/Components/Touchpoints/Types/HybridCarousel/Container/MLBusinessHybridCarouselDataHandler.swift
Fixed Hybrid Carousel height on Store Cards. Fixed reuse.
> Fixed Hybrid Carousel height on Store Cards. Fixed reuse.

- Source/Components/Touchpoints/Types/CoverCarousel/Carousel/MLBusinessCoverCarouselView.swift
Este **PR** simplemente corrige los valores por default de animación del alpha de las cards en el carousel, y de la animación de tap en las mismas, para el caso en que dichas propiedades vengan como `nil` en el modelo.
> Default Values for Cover Carousel

- Example/Example_BusinessComponents.xcodeproj/project.pbxproj
- Example/Example_BusinessComponents/MockData/CoverCarouselData.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Card/MLBusinessCoverCarouselItemContentModelMapper.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Card/MLBusinessCoverCarouselItemModel.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Card/MLBusinessCoverCarouselItemView.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Card/MLBusinessCoverCarouselViewCell.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Carousel/MLBusinessCoverCarouselModel.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Carousel/MLBusinessCoverCarouselView.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Touchpoint/MLBusinessTouchpointsCoverCarouselView.swift
Este **PR** agrega:
- Workaround para el cómputo de la altura de una `HybridRow`, necesario para resolver la altura de las cards del `CoverCarousel`. 
- Reestructuración de los modelos para el `CoverCarousel`.
> Cover Carousel Fixes

- Source/Components/MultipleDescription/MLBusinessMultipleDescriptionView.swift
- Source/Components/Row/MLBusinessRowView.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Card/MLBusinessCoverCarouselItemView.swift
Este **PR** simplemente expone a la property `imageProvider` del componente _Row_. De esta manera quedan seteables desde afuera.
> Expose Image Provider in Row

- CHANGELOG.md
- Example/Example_BusinessComponents/MockData/RowData.swift
- Example/Podfile
- Source/Components/Row/MLBusinessRowData.swift
- Source/Components/Row/MLBusinessRowView.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Card/MLBusinessCoverCarouselItemContentModelMapper.swift
- Source/Components/Touchpoints/Types/CoverCarousel/Card/MLBusinessCoverCarouselItemModel.swift
- Source/Components/Touchpoints/Types/MultipleRow/MLBusinessTouchpointsMultipleRowModel.swift
- Se permite grisar el título y el subtítulo de la HybridRow desde BE.
> Added hybrid row title and subtitle grayed

- CHANGELOG.md
- Source/Components/Row/MLBusinessRowData.swift
- Source/Components/Row/MLBusinessRowView.swift
- Se agrega el atributo `main_label_top` a la row híbrida. 
> Hybrid Row Changes

- CHANGELOG.md
- Source/Components/Item Description/MLBusinessItemDescriptionData.swift
Se agrega el método `getOptionalIconHexaColor()` a `MLBusinessItemDescriptionData` para soporte de DTOs con `primary_color == nil` en los que se requiera renderizar la imagen con sus colores originales.
Se decidió adjuntar este método en lugar de modificar el ya existente `getIconHexaColor()` para evitar romper la firma del protocolo y generar incompatibilidades entre módulos.
- [MER-6561](https://mercadolibre.atlassian.net/browse/MER-6561)
> Add optional icon color support on item description data

- Source/Components/Item Description/MLBusinessItemDescriptionData.swift
Se quita la implementación default de `getOptionalIconHexaColor()` porque trajo problemas en la implementación propia de las clases que cumplen el protocolo.
- [MER-6561](https://mercadolibre.atlassian.net/browse/MER-6561)
> Fix item optional color support

- CHANGELOG.md
- Source/Components/Item Description/MLBusinessItemDescriptionView.swift
El método [`getIconHexaColor()`](https://github.com/mercadolibre/fury_homes-ios/blob/17f5bb5d4ffe4ba2881e7da25123d2a5c372629e/LibraryComponents/Classes/v2/Feed/Model/MLHomeIconDescription.swift#L48) de `MLHomeIconDescription` devuelve siempre un color hexadecimal (cuando el modelo tiene `primaryColor == nil`, defaultea a `"FFFFFF"`).
Para utilizar iconos con colores propios, necesitamos diferenciar modelos con `primaryColor == nil` y así poder ejecutar [esta línea](https://github.com/mercadolibre/mlbusiness-components-ios/blob/ae88b0e1940de2bf74278687a52ca01d34e32240/Source/Components/Item%20Description/MLBusinessItemDescriptionView.swift#L87) que muestra la imagen correctamente, sin alterarla.
Se propone utilizar [`getOptionalIconHexaColor()`](https://github.com/mercadolibre/fury_homes-io …
> [MER-6561] Arreglar muestra de imágenes en componente de beneficios de homes

- CHANGELOG.md
- Source/Components/Touchpoints/Types/Carousel/MLBusinessCarouselContainerView .swift
- Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselContainerItemView.swift
- Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselContainerViewCell.swift
- Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselView.swift
- Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCollectionViewDataHandler.swift
**Probletica:**
O carrossel de "Descobrir Locais" na Home do MercadoPago estava sendo ignorado pelo Voice Over
**Solução:**
O Voice Over sempre tenta ler o objetivo mais acima na hierarquia, porem como nossa célula está níveis hierárquicos mais a baixo, foi desativado nas camadas superiores a acessibilidade da view, deixando apenas as células visíveis.
Essa PR tem dependencia com a PR
https://github.com/mercadolibre/fury_instore-home-sections-ios/pull/87
**Antes:**
**Depois:**
> Arruma a forma que VoiceOver le os itens no carrossel

- Source/Components/Touchpoints/Types/Carousel/MLBusinessTouchpointsCarouselContainerItemView.swift
Fix size of text in Touchpoints full card type 
before |  after 
--------- | -------- 
> Fix touchpoints full card issue

- CHANGELOG.md
- Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemView.swift
Metodo prepareForReuse no estaba implementado correctamente, se estaban pisando los wordings que llegaban de be para los casos donde un texto venia en nil.
> Fix Touchpoint Cell Reuse

- CHANGELOG.md
- MLBusinessComponents.podspec
- Source/Components/Item Description/MLBusinessItemDescriptionView.swift
Se permite que el componente MLBusinessItemDescriptionView pueda tener textos de 3 lineas. Adaptandose a los beneficios que puede llegar a mostrar Loyalty en su componente
> Change number of lines in Business Item Description

- CHANGELOG.md
- Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemView.swift
Fix para casos border en donde desde be podríamos no tener los valores de text_color para los labels del FlexCoverCarousel. También se toma en cuenta el caso en donde no tenemos text para la pill, en ese caso ahora ocultamos esa vista.
|Antes| Después|
|-----|----| 
|![Simulator Screen Recording - iPhone 13 - 2022-08-17 at 12 16 44](https://user-images.githubusercontent.com/97110592/185182110-f81b979f-366f-4f44-a3c8-413a7c92d20e.gif)|![Simulator Screen Recording - iPhone 13 - 2022-08-17 at 11 42 51](https://user-images.githubusercontent.com/97110592/185182196-cdd648e0-34c8-46c1-832d-67064fcfdc71.gif)|
> Fix Label Text Color - FlexCoverCarousel

- CHANGELOG.md
- Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemModel.swift
Se corrige bug visual que hacia que la card del FlexCoverCarousel se vea en blanco cuando un objeto de texto venia desde como nil. 
ejemplo: 
`"title": {
},
"subtitle": {
},`
| Antes | Despues |
|--|------|
|![Simulator Screen Shot - iPhone 13 - 2022-08-16 at 17 34 25 copia](https://user-images.githubusercontent.com/97110592/184985017-258d06b0-187d-4d81-a37e-e87f8ebff2c1.jpg)| ![Simulator Screen Shot - iPhone 13 - 2022-08-16 at 18 06 21](https://user-images.githubusercontent.com/97110592/184985219-bd415d68-b038-430d-98bf-cc4cd955f217.png)|
> Fix para textos en nil - FlexCoverCarousel

- CHANGELOG.md
- Source/Components/Touchpoints/Types/FlexCoverCarousel/Carousel/MLBusinessFlexCoverCarouselView.swift
Se corrige defecto en trackprints para el componente FlexCoverCarousel
> [Flex Cover Carousel] - Fix Tracking

- CHANGELOG.md
- Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemView.swift
- Se mueven los logos a la parte superior
- Se modifica el espacio horizontal para los elementos dentro de la card.
| iPhone SE | iPhone 13 Pro Max |
|-----------|-------------------|
|  <img width="350" alt="se" src="https://user-images.githubusercontent.com/45976466/200909779-811b8c8b-0957-4689-97a0-329622a06e80.png">  |  <img width="400" alt="max" src="https://user-images.githubusercontent.com/45976466/200912872-7c59690e-f07d-4735-bf30-8edf38dd873b.png">  |
|    |  <img width="400" alt="max2" src="https://user-images.githubusercontent.com/45976466/200913330-4052e691-b73e-4cd6-afcc-115b2f7040d6.png">  |
> [CHANGE] Se modifica la posición de elementos de FlexCoverCarousel

- CHANGELOG.md
- Example/Example_BusinessComponents/MockData/RowData.swift
- Source/Commons/MLBusinessAccessibilityUtils.swift
- Source/Components/MultipleDescription/MLBusinessMultipleDescriptionView.swift
- Source/Core/Extensions/String+Extension.swift
Se realizan ajustes de accesibilidad en la MultipleDescriptionView para que la moneda sea interpretada como "peso" o "real" por el VoiceOver y no como "dolar".
MDS: VSP - Accessibility prices (MP + Instore)
https://user-images.githubusercontent.com/85568138/204386585-31a294ac-1fea-45d0-ae84-fc8ed0340ced.mov
https://user-images.githubusercontent.com/85568138/204386639-c79dc913-1a82-4c11-91c5-ee3e78de76c6.mov
> Accessibility on MultipleDescriptionView

- CHANGELOG.md
- Source/Components/Touchpoints/Types/FlexCoverCarousel/Card/MLBusinessFlexCoverCarouselItemView.swift
- Se soporta el modo "solo imagen" en las cards de FlexCoverCarousel
- Ahora el color del gradiente puede venir de BE
> FlexCoverCarousel Improves

- CHANGELOG.md
- Source/Components/Touchpoints/Types/DynamicCoverCarousel/Card/MLBusinessDynamicCoverCarouselItemModel.swift
Se agrega valor por defecto para multimedia_cover para no afectar a otras libs
> [Fix] Default value for MultimediaCover

- CHANGELOG.md
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesView.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesViewModel.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesWebView.swift
- Source/Components/Touchpoints/Types/DynamicCoverCarousel/Card/MLBusinessDynamicCoverCarouselItemView.swift
- Source/Components/Touchpoints/Types/DynamicCoverCarousel/Card/MLBusinessDynamicCoverCarouselViewCell.swift
- Source/Components/Touchpoints/Types/DynamicCoverCarousel/Carousel/MLBusinessDynamicCoverCarouselView.swift
Para esta version se implementa play/pause automatica para cuando la card del carousel cambia el estado del foco de la card.
| antes `v1` | despues `v2` |
|----|-----|
| ![Simulator Screen Recording - iPhone 13 - 2022-12-16 at 09 50 56](https://user-images.githubusercontent.com/97110592/209865862-86365fd6-0ac6-450f-abfb-f96db3e9fc85.gif) | ![Simulator Screen Recording - iPhone 13 - 2022-12-28 at 17 06 13](https://user-images.githubusercontent.com/97110592/209866545-9b625619-ca4f-4fa1-9203-3cad8aa76a61.gif)|
> [LIVE-IMAGES] v2 Play/Pause Automatic when cards changes focus status

- CHANGELOG.md
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesProvider.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesView.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesViewModel.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesWebView.swift
Se agrega soporte para cachear las imagenes animadas en formato webp y cambiamos el load del webview para que consuma el archivo ya descargado.
> [Live Images] Download + Cache Solution

- CHANGELOG.md
- Source/Components/Touchpoints/LiveImages/ImageAnimationManager.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessBatterySavingUtils.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesCarousel.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessLiveImagesModel.swift
- Source/Components/Touchpoints/LiveImages/MLBusinessWifiUtils.swift
- Source/Components/Touchpoints/Types/DynamicCoverCarousel/Carousel/MLBusinessDynamicCoverCarouselView.swift
Se agrega validación para no configurar imagenes animadas cuando el device no esta conectado a wifi o tiene poca bateria.
> [LIVE IMAGES] Support validation for saving battery and celular data
